
codecov:

coverage:
    precision: 2
    round: down
    range: "70...100"
    status:
    project:
        default:
        # basic
        target: auto
        threshold: null
        base: auto
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
        patch: yes
        changes: no

parsers:
    gcov:
        branch_detection:
        conditional: yes
        loop: yes
        method: no
        macro: no

ignore:
- Showcase-iOS/AppDelegate.*
- Showcase-iOS/*ViewController.*
- Showcase-iOS/*.storyboard
- "Showcase-iOSTests/*"
- Showcase-iOS/Login/View/.*
- Showcase-iOS/Contact Us/View/.*
- Showcase-iOS/Contact Us/View/ViewHelpers/.*
- Showcase-iOS/Dashboard/View/.*

comment:
    layout: "header, diff, flags, files, footer"
    behavior: default
    require_changes: false  # if true: only post the comment if coverage changes
    branches: null
    flags: null
    paths: null
